language: node_js
sudo: false
node_js:
  - '7'
before_script:
  - yarn build
script:
  - yarn travis

deploy:
 - provider: script
   script: NODE_ENV=production yarn build
   skip_cleanup: true
 - provider: surge
   project: ./dist
   domain: csc360-questionnaire.surge.sh
   skip_cleanup: true
